version: "1.0"
info:
  model: int-scaffold
packages:
- name: DigitalCardIssuanceStageProject
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: customCobrandingService
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: DeliveryPartner
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: CardTypeSecurity
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: cardIssuance
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: NotificationPackage
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: SalesforceConn
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
