version: "1.0"
info:
  model: int-scaffold
packages:
- name: DigitalCardIssuanceStageProject
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: CardIssuancePublicServices
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: customCobrandingService
  gitServerName: vikashGithub
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
